import os
import logging
from pathlib import Path
from datetime import datetime, timedelta
import yaml

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class ProductivityAnalysis:
    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.reports_dir = self.vault_path / "Reports" / "Productivity"
        self.done_dir = self.vault_path / "Done"
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def scan_completed_tasks(self, days=7):
        """Scans the Done folder for completed tasks."""
        cutoff = datetime.now() - timedelta(days=days)
        tasks = []
        
        if not self.done_dir.exists():
            return tasks
            
        for file in self.done_dir.glob("*.md"):
            try:
                mtime = datetime.fromtimestamp(file.stat().st_mtime)
                if mtime > cutoff:
                    # Basic extraction
                    tasks.append({
                        "name": file.name,
                        "date": mtime.strftime("%Y-%m-%d"),
                    })
            except Exception as e:
                logger.error(f"Error scanning task {file}: {e}")
                
        return tasks

    def generate_report(self):
        tasks = self.scan_completed_tasks()
        
        report_date = datetime.now().strftime("%Y-%m-%d")
        filename = f"Productivity_Report_{report_date}.md"
        report_path = self.reports_dir / filename
        
        content = f"""---
type: productivity_report
date: {report_date}
tasks_completed: {len(tasks)}
---

# Productivity Analysis Report - {report_date}

## 1. Overview
- **Tasks Completed (Last 7 Days):** {len(tasks)}

## 2. Completed Tasks Breakdown
| Task | Completion Date |
|---|---|
"""
        for task in tasks:
            content += f"| {task['name']} | {task['date']} |\n"
            
        content += "\n## 3. Analysis & Velocity\n"
        if len(tasks) > 5:
            content += "- **High Productivity:** Task velocity is above average.\n"
        else:
            content += "- **Steady Pace:** Velocity is consistent but room for improvement.\n"
            
        content += f"\n\n*Generated by AI Business Intelligence Module*"
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        logger.info(f"Productivity report generated: {report_path}")
        return report_path

if __name__ == "__main__":
    analysis = ProductivityAnalysis("AI-Employee-Vault")
    analysis.generate_report()
