"""
Task Processor Demo - Process files from Needs_Action folder
"""

from pathlib import Path
from datetime import datetime

# Paths
VAULT_FOLDER = Path("D:/Gemini_Cli/hackathon/hackathon_0/AI-Employee/AI-Employee-Vault")
NEEDS_ACTION = VAULT_FOLDER / "Needs_Action"
PLANS = VAULT_FOLDER / "Plans"

print("=" * 60)
print("AI Employee - Task Processor Demo")
print("=" * 60)
print()

# Ensure Plans folder exists
PLANS.mkdir(parents=True, exist_ok=True)

print(f"Vault: {VAULT_FOLDER}")
print(f"Needs Action: {NEEDS_ACTION}")
print(f"Plans: {PLANS}")
print()

# Find files in Needs_Action
print("Scanning Needs_Action folder...")
md_files = list(NEEDS_ACTION.glob("*.md"))

if md_files:
    print(f"Found {len(md_files)} file(s) to process:")
    for f in md_files:
        print(f"  - {f.name}")
    print()
    
    # Process each file
    for file in md_files:
        print(f"Processing: {file.name}")
        print("-" * 40)
        
        # Read file content
        content = file.read_text(encoding='utf-8')
        print(f"Content length: {len(content)} characters")
        
        # Extract title from first line
        title = content.split('\n')[0].replace('#', '').strip()
        print(f"Title: {title}")
        
        # Generate plan filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        plan_filename = f"plan_{file.stem}_{timestamp}.md"
        plan_path = PLANS / plan_filename
        
        # Create plan content (mock - in real implementation this would use Gemini/Claude)
        plan_content = f"""# Plan: {title}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Source:** {file.name}
**Status:** Draft

## Overview
This plan was automatically generated based on the input file.

## Proposed Approach

### Phase 1: Analysis
- Review requirements
- Identify stakeholders
- Gather resources

### Phase 2: Planning
- Create detailed timeline
- Allocate resources
- Define milestones

### Phase 3: Execution
- Implement plan
- Monitor progress
- Adjust as needed

### Phase 4: Review
- Evaluate outcomes
- Document learnings
- Archive results

## Next Steps
1. Review and approve this plan
2. Assign resources
3. Set start date
4. Begin Phase 1

---
*Generated by AI Employee Bronze Tier*
"""
        
        # Write plan file
        plan_path.write_text(plan_content, encoding='utf-8')
        print(f"Plan created: {plan_filename}")
        print()
    
    print("=" * 60)
    print(f"Processed {len(md_files)} file(s)")
    print(f"Plans created in: {PLANS}")
    print("=" * 60)
else:
    print("No files to process in Needs_Action folder")
    print()

print()
print("Demo Complete!")
