/**
 * Plan Types
 * Type definitions for AI-generated plan entities
 */

/**
 * A section within a plan containing steps
 */
export interface PlanSection {
  title: string;         // 1-100 characters
  steps: string[];       // 1-20 steps, each 1-500 characters
}

/**
 * Plan entity generated by AI
 */
export interface Plan {
  id: string;            // UUID v4
  taskId: string;        // UUID v4 (references Task)
  sections: PlanSection[];
  summary: string;       // 1-500 characters
  createdAt: string;     // ISO-8601 datetime
}

/**
 * Input for generating a plan
 */
export interface GeneratePlanInput {
  taskIds: string[];     // Array of task UUIDs to plan for
}

/**
 * Response when plan generation is in progress
 */
export interface PlanGenerationStatus {
  status: 'processing';
  estimatedCompletion?: string;  // ISO-8601 datetime (optional)
}
