"""initial_schema

Revision ID: 377f3ebb0c69
Revises: 
Create Date: 2026-03-16 22:13:15.278208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '377f3ebb0c69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityLog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activitylog_timestamp', 'ActivityLog', ['timestamp'], unique=False)
    op.create_index('ix_activitylog_type', 'ActivityLog', ['type'], unique=False)
    op.create_table('Goal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_createdAt', 'Goal', ['createdAt'], unique=False)
    op.create_index('ix_goal_state', 'Goal', ['state'], unique=False)
    op.create_table('MemoryRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('goalId', sa.String(), nullable=True),
    sa.Column('taskId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memoryrecord_createdAt', 'MemoryRecord', ['createdAt'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('lastActivity', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goalId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('assignedAgent', sa.String(), nullable=True),
    sa.Column('dependsOn', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goalId'], ['Goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_createdAt', 'Task', ['createdAt'], unique=False)
    op.create_index('ix_task_status', 'Task', ['status'], unique=False)
    op.create_table('AgentExecution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('taskId', sa.String(), nullable=False),
    sa.Column('agentName', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('toolCalls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agentexecution_agentName', 'AgentExecution', ['agentName'], unique=False)
    op.create_index('ix_agentexecution_taskId', 'AgentExecution', ['taskId'], unique=False)
    op.create_table('Plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('taskId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskId')
    )
    op.create_index('ix_plan_status', 'Plan', ['status'], unique=False)
    op.create_table('CostLog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agentExecutionId', sa.String(), nullable=True),
    sa.Column('modelName', sa.String(), nullable=False),
    sa.Column('tokensIn', sa.Integer(), nullable=False),
    sa.Column('tokensOut', sa.Integer(), nullable=False),
    sa.Column('estimatedCostUsd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agentExecutionId'], ['AgentExecution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_costlog_createdAt', 'CostLog', ['createdAt'], unique=False)
    op.create_table('PlanStep',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('planId', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('estimatedDuration', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['Plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planstep_order', 'PlanStep', ['order'], unique=False)
    op.create_index('ix_planstep_planId', 'PlanStep', ['planId'], unique=False)
    op.create_table('ToolInvocation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agentExecutionId', sa.String(), nullable=False),
    sa.Column('toolName', sa.String(), nullable=False),
    sa.Column('arguments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('riskScore', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agentExecutionId'], ['AgentExecution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_toolinvocation_status', 'ToolInvocation', ['status'], unique=False)
    op.create_index('ix_toolinvocation_toolName', 'ToolInvocation', ['toolName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_toolinvocation_toolName', table_name='ToolInvocation')
    op.drop_index('ix_toolinvocation_status', table_name='ToolInvocation')
    op.drop_table('ToolInvocation')
    op.drop_index('ix_planstep_planId', table_name='PlanStep')
    op.drop_index('ix_planstep_order', table_name='PlanStep')
    op.drop_table('PlanStep')
    op.drop_index('ix_costlog_createdAt', table_name='CostLog')
    op.drop_table('CostLog')
    op.drop_index('ix_plan_status', table_name='Plan')
    op.drop_table('Plan')
    op.drop_index('ix_agentexecution_taskId', table_name='AgentExecution')
    op.drop_index('ix_agentexecution_agentName', table_name='AgentExecution')
    op.drop_table('AgentExecution')
    op.drop_index('ix_task_status', table_name='Task')
    op.drop_index('ix_task_createdAt', table_name='Task')
    op.drop_table('Task')
    op.drop_table('system_state')
    op.drop_index('ix_memoryrecord_createdAt', table_name='MemoryRecord')
    op.drop_table('MemoryRecord')
    op.drop_index('ix_goal_state', table_name='Goal')
    op.drop_index('ix_goal_createdAt', table_name='Goal')
    op.drop_table('Goal')
    op.drop_index('ix_activitylog_type', table_name='ActivityLog')
    op.drop_index('ix_activitylog_timestamp', table_name='ActivityLog')
    op.drop_table('ActivityLog')
    # ### end Alembic commands ###
